### ISSUE TITLE
It can not create 2 alerts with same description and everything else different.

### ISSUE THREAD

**Issue by amolsh** [draios/python-sdc-client#24]
Hi, 
I am not sure weather it is intended behaviour or bug. I tried to create 2 alerts having different name and configuration but same description. It gives **alert already exists** error.
Use-case was, I was putting my runbook url in all alert descriptions. But, as all alert description were same, only one alert got created and other throws  **alert already exists** error.

**Comment by philrz** [comment]
@amolsh,

Duplicate descriptions should work now. Also, since we've stacked up a couple fixes, I went ahead and created a new release version, so the one you get when you `pip install sdcclient` should include the fix for this as well as the recent support for WEBHOOK notification channels. I'll go ahead and close this issue now.
