### ISSUE TITLE
update_alert example

### ISSUE THREAD

**Issue by azafred** [draios/python-sdc-client#31]
Hello, I am trying to get update_alert going, since it would be a useful inclusion in our deployment process, but while playing in bpython, it seems update_alert is not an attribute of SdcClient:

AttributeError: SdcClient instance has no attribute 'update_alert'

I am running with the latest version as of this writing:
sdcclient==0.5.2

**Comment by azafred** [comment]
The problem must be with my implementation since I clearly see the function is defined... 
Ignore me....

**Comment by azafred** [comment]
(seems like the pypi version is not up to date with the git repo, as installing from github exposes update_alert)

**Comment by philrz** [comment]
@azafred, yes, you are correct. I only just recently added that function and was waiting for feedback from the original requester before finalizing a new release and pushing it to pypi. FWIW, that person has just responded saying he has some potential improvements in mind, so I'm inclined to wait and see if he submits a new PR. Since it sounds like you're up & running for now with what you pulled from GitHub, feel free to let me know any feedback you have.

**Comment by azafred** [comment]
I happened to go to the closed comments and saw that ;p 
Sorry for jumping the gun! 

In any case, thank you for all the work! it is greatly appreciated. So far no issues, but I have only been playing in bpython to scratch the surface. Going to start implementing things now, so I'll definitely let you know if I see anything worth mentioning! 

Cheers!
